services:
  hello-world:
    build: 
      context: .
      target: development
    image: hello-world
    container_name: hello-world
    ports:
      - "3008:3008"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json